# Welcome to Jekyll!
title: Desafio Mundial 
email: info@odicforcesounds.com 
description: Um desafio que irá fazer a mudança necessária do mundo e das sociedades
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://wiki.odicforcesounds.com" 
github_username: odicforcesounds

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
