# Welcome to Jekyll!
title: Desafio Mundial
email: info@odicforcesounds.com 
description: Um desafio que se foca na necessidade da mudança comportamental da industria em geral. Um sistema que apresenta um novo conceito de economia, que quer potenciar as qualidades de todas os participantes.
baseurl: "/"
url: "https://wiki.odicforcesounds.com" # the base hostname & protocol for your site, e.g. http://example.com
  #twitter_username: jekyllrb
github_username:  odicforcesounds

# Build settings
theme: minima
# plugins:
#   - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
